### PR TITLE
Use read_unaligned() in the header decoding test

### LINKED ISSUE #455: Use `read_unaligned()` in the header decoding test
Currently the test `decode_header()` crashes in MacOS while it works in windows and linux. [code](https://github.com/postech-dao/simperby/blob/main/core/src/hash.rs#L178)

This is NOT because MacOS is somewhat different, but actually we have performed an undefined behavior (UB).
- in unsafe rust, dereferencing an unaligned pointer is UB.
- however, it can be mitigated by using `read_unaligned()` instead.
- Please fix `let x = (*p).clone();` to use `read_unaligned()` instead, in the `read()` function that is used by the `decode_header` test.

### PR DESCRIPTION
**Pull request by sejongk**
fixes #455 

use read_unaligned() instead of dereferencing the unaligned pointer to mitigate the undefined behavior.

### CODE REVIEW

File: core/src/hash.rs [hunk 1]
```diff
@@ -165,11 +165,12 @@ mod tests {
     use super::*;
     use crate::serde_spb;
     use std::mem::size_of;
+    use std::ptr::read_unaligned;
 
     unsafe fn read<T: Clone>(offset: &mut usize, data: &[u8]) -> T {
         let size = size_of::<T>();
         let p = data[*offset..*offset + size].as_ptr() as *const T;
-        let x = (*p).clone();
+        let x = read_unaligned(p);
```
Comment (sigridjineth) [inline core/src/hash.rs:173]: thanks for your contribution!

**Review by sigridjineth — APPROVED** [review]
